resources:
- https://raw.githubusercontent.com/intel/xpumanager/V1.2.18/deployment/kubernetes/daemonset-intel-xpum.yaml
namespace: monitoring
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: kustom/kustom_xpumanager.yaml
