apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nfd-master
  path: master-args.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: nfd-master
  path: master-rbac.yaml
