apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: master-args.yaml
  target:
    group: apps
    kind: Deployment
    name: nfd-master
    version: v1
- path: master-rbac.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: nfd-master
    version: v1
