nameSuffix: -crypto-perf
resources:
- ../dpdk-test/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: test.json
  target:
    kind: Pod
    name: qat-dpdk
    version: v1
