nameSuffix: -compress-perf
resources:
- ../dpdk-test/
configMapGenerator:
- files:
  - file.txt
  name: test-data
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: volume_add_configmap.yaml
- path: env_replace_testcmd.yaml
