nameSuffix: -test
resources:
- ../../base/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: containers_patch_command_args.json
  target:
    kind: Pod
    name: qat-dpdk
    version: v1
