nameSuffix: -tc1
resources:
- ../patches/crypto-perf
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: tc1.json
  target:
    kind: Pod
    name: qat-dpdk
    version: v1
