apiVersion: apps/v1
kind: Deployment
metadata:
  name: inteldeviceplugins-controller-manager
  namespace: inteldeviceplugins-system
spec:
  template:
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --devices=fpga
        name: manager
