apiVersion: v1
kind: Pod
metadata:
  name: iaa-qpl-demo
spec:
  containers:
  - name: iaa-qpl-demo
    image: iaa-qpl-demo:devel
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        iaa.intel.com/wq-user-dedicated: 1
        iaa.intel.com/wq-user-shared: 1
        cpu: 1

  restartPolicy: Never
