apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: inproc-
resources:
- ../sgx_ecdsa_aesmd_quote
commonAnnotations:
  sgx.intel.com/quote-provider: intelsgx-demo-job-1
configMapGenerator:
- files:
  - sgx_default_qcnl.conf
  name: sgx-attestation-conf
patches:
- path: add_hostnetwork.yaml
- path: add_sgx_default_qcnl_conf.yaml
