resources:
- ../../base/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: volumes_patch.yaml
  target:
    group: apps
    kind: DaemonSet
    name: intel-vpu-plugin
    version: v1
- path: add_command_args.yaml
