name: e2e-iaa
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches:
      - main
      - 'release-*'

env:
  IMAGES: 'intel-iaa-plugin intel-idxd-config-initcontainer accel-config-demo'

permissions:
  contents: read

jobs:
  e2e-iaa:
    name: e2e-iaa
    runs-on: [simics-spr]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: $IMAGES"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
