name: e2e-gpu
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main
      - 'release-*'

env:
  IMAGES: 'intel-gpu-plugin intel-gpu-initcontainer'

jobs:
  e2e-gpu:
    name: e2e-gpu
    runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: $IMAGES"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
