name: "OSSF"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-24.04

    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: "Analyze project"
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload results to security"
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b # v3
        with:
          sarif_file: results.sarif
