name: "OSSF"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-24.04

    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: "Analyze project"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Upload results to security"
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3
        with:
          sarif_file: results.sarif
